### ISSUE TITLE
【feature不生效】5个问题

### ISSUE THREAD

**Issue by estrm** [henryhuang/hexo-theme-polarbearsimple#11]
你好，henryhuang。我使用polarbearsimple主题，遇到如下几个问题。

1. 目录设置： TOC [ ]；没有成功显示；
2. disqus_shortname评论，不显示；
3. Tags页面不显示；例如，https://guguant.github.io/tags/
4. copyright 版权信息，不显示；
5. 社交图标：没有显示；

**polarbearsimple/_config.yml** 文件配置如下：
```yml
# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2019

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: 
  Tags: /tags
  Categories: /categories
  Story: /story
  About: /about


# ===========================================
# Widget Settings
# ===========================================
# widget function
# false: disable
# widget_custom: custom your widget
#   title: your widget title
#   content: Add your html code in here. Example: <p>Hello, I am Frost</p>
widget:
  Tags: true
  Categories: false
  Custom: false

widget_custom:
    title: Test
    content: <p>testing...</p>

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Cobalt Blue #Default
  fancybox: false

# ===========================================
# Third Party Services Settings
# ===========================================

# Baidu Analytics
baidu_analytics:
# Google Analytics
google_analytics:

# Duoshuo
duoshuo_shortname:
# Disqus
disqus_shortname: gotum


# ===========================================
# Version
# ===========================================
version: 1.1

toc: true

# copyright
copyright:
  enable: true
  # https://creativecommons.org/
  license: '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

# social
social:
  github: https://github.com/Guguant
  instagram: https://www.instagram.com/sea_andyz
```
